# NeetCode 150 problem catalog. (topic, name, difficulty)
# Order within each topic matches NeetCode's roadmap.
NEETCODE_150 = [
    # Arrays & Hashing (9)
    ("Arrays & Hashing", "Contains Duplicate", "easy"),
    ("Arrays & Hashing", "Valid Anagram", "easy"),
    ("Arrays & Hashing", "Two Sum", "easy"),
    ("Arrays & Hashing", "Group Anagrams", "medium"),
    ("Arrays & Hashing", "Top K Frequent Elements", "medium"),
    ("Arrays & Hashing", "Encode and Decode Strings", "medium"),
    ("Arrays & Hashing", "Product of Array Except Self", "medium"),
    ("Arrays & Hashing", "Valid Sudoku", "medium"),
    ("Arrays & Hashing", "Longest Consecutive Sequence", "medium"),
    # Two Pointers (5)
    ("Two Pointers", "Valid Palindrome", "easy"),
    ("Two Pointers", "Two Sum II - Input Array Is Sorted", "medium"),
    ("Two Pointers", "3Sum", "medium"),
    ("Two Pointers", "Container With Most Water", "medium"),
    ("Two Pointers", "Trapping Rain Water", "hard"),
    # Sliding Window (6)
    ("Sliding Window", "Best Time to Buy and Sell Stock", "easy"),
    ("Sliding Window", "Longest Substring Without Repeating Characters", "medium"),
    ("Sliding Window", "Longest Repeating Character Replacement", "medium"),
    ("Sliding Window", "Permutation in String", "medium"),
    ("Sliding Window", "Minimum Window Substring", "hard"),
    ("Sliding Window", "Sliding Window Maximum", "hard"),
    # Stack (7)
    ("Stack", "Valid Parentheses", "easy"),
    ("Stack", "Min Stack", "medium"),
    ("Stack", "Evaluate Reverse Polish Notation", "medium"),
    ("Stack", "Generate Parentheses", "medium"),
    ("Stack", "Daily Temperatures", "medium"),
    ("Stack", "Car Fleet", "medium"),
    ("Stack", "Largest Rectangle in Histogram", "hard"),
    # Binary Search (7)
    ("Binary Search", "Binary Search", "easy"),
    ("Binary Search", "Search a 2D Matrix", "medium"),
    ("Binary Search", "Koko Eating Bananas", "medium"),
    ("Binary Search", "Find Minimum in Rotated Sorted Array", "medium"),
    ("Binary Search", "Search in Rotated Sorted Array", "medium"),
    ("Binary Search", "Time Based Key-Value Store", "medium"),
    ("Binary Search", "Median of Two Sorted Arrays", "hard"),
    # Linked List (11)
    ("Linked List", "Reverse Linked List", "easy"),
    ("Linked List", "Merge Two Sorted Lists", "easy"),
    ("Linked List", "Reorder List", "medium"),
    ("Linked List", "Remove Nth Node From End of List", "medium"),
    ("Linked List", "Copy List with Random Pointer", "medium"),
    ("Linked List", "Add Two Numbers", "medium"),
    ("Linked List", "Linked List Cycle", "easy"),
    ("Linked List", "Find the Duplicate Number", "medium"),
    ("Linked List", "LRU Cache", "medium"),
    ("Linked List", "Merge K Sorted Lists", "hard"),
    ("Linked List", "Reverse Nodes in K-Group", "hard"),
    # Trees (15)
    ("Trees", "Invert Binary Tree", "easy"),
    ("Trees", "Maximum Depth of Binary Tree", "easy"),
    ("Trees", "Diameter of Binary Tree", "easy"),
    ("Trees", "Balanced Binary Tree", "easy"),
    ("Trees", "Same Tree", "easy"),
    ("Trees", "Subtree of Another Tree", "easy"),
    ("Trees", "Lowest Common Ancestor of a Binary Search Tree", "medium"),
    ("Trees", "Binary Tree Level Order Traversal", "medium"),
    ("Trees", "Binary Tree Right Side View", "medium"),
    ("Trees", "Count Good Nodes in Binary Tree", "medium"),
    ("Trees", "Validate Binary Search Tree", "medium"),
    ("Trees", "Kth Smallest Element in a BST", "medium"),
    ("Trees", "Construct Binary Tree from Preorder and Inorder Traversal", "medium"),
    ("Trees", "Binary Tree Maximum Path Sum", "hard"),
    ("Trees", "Serialize and Deserialize Binary Tree", "hard"),
    # Tries (3)
    ("Tries", "Implement Trie (Prefix Tree)", "medium"),
    ("Tries", "Design Add and Search Words Data Structure", "medium"),
    ("Tries", "Word Search II", "hard"),
    # Heap / Priority Queue (7)
    ("Heap / Priority Queue", "Kth Largest Element in a Stream", "easy"),
    ("Heap / Priority Queue", "Last Stone Weight", "easy"),
    ("Heap / Priority Queue", "K Closest Points to Origin", "medium"),
    ("Heap / Priority Queue", "Kth Largest Element in an Array", "medium"),
    ("Heap / Priority Queue", "Task Scheduler", "medium"),
    ("Heap / Priority Queue", "Design Twitter", "medium"),
    ("Heap / Priority Queue", "Find Median from Data Stream", "hard"),
    # Backtracking (9)
    ("Backtracking", "Subsets", "medium"),
    ("Backtracking", "Combination Sum", "medium"),
    ("Backtracking", "Permutations", "medium"),
    ("Backtracking", "Subsets II", "medium"),
    ("Backtracking", "Combination Sum II", "medium"),
    ("Backtracking", "Word Search", "medium"),
    ("Backtracking", "Palindrome Partitioning", "medium"),
    ("Backtracking", "Letter Combinations of a Phone Number", "medium"),
    ("Backtracking", "N-Queens", "hard"),
    # Graphs (13)
    ("Graphs", "Number of Islands", "medium"),
    ("Graphs", "Max Area of Island", "medium"),
    ("Graphs", "Clone Graph", "medium"),
    ("Graphs", "Walls and Gates", "medium"),
    ("Graphs", "Rotting Oranges", "medium"),
    ("Graphs", "Pacific Atlantic Water Flow", "medium"),
    ("Graphs", "Surrounded Regions", "medium"),
    ("Graphs", "Course Schedule", "medium"),
    ("Graphs", "Course Schedule II", "medium"),
    ("Graphs", "Redundant Connection", "medium"),
    ("Graphs", "Number of Connected Components in an Undirected Graph", "medium"),
    ("Graphs", "Graph Valid Tree", "medium"),
    ("Graphs", "Word Ladder", "hard"),
    # Advanced Graphs (6)
    ("Advanced Graphs", "Reconstruct Itinerary", "hard"),
    ("Advanced Graphs", "Min Cost to Connect All Points", "medium"),
    ("Advanced Graphs", "Network Delay Time", "medium"),
    ("Advanced Graphs", "Swim in Rising Water", "hard"),
    ("Advanced Graphs", "Alien Dictionary", "hard"),
    ("Advanced Graphs", "Cheapest Flights Within K Stops", "medium"),
    # 1D DP (12)
    ("1D DP", "Climbing Stairs", "easy"),
    ("1D DP", "Min Cost Climbing Stairs", "easy"),
    ("1D DP", "House Robber", "medium"),
    ("1D DP", "House Robber II", "medium"),
    ("1D DP", "Longest Palindromic Substring", "medium"),
    ("1D DP", "Palindromic Substrings", "medium"),
    ("1D DP", "Decode Ways", "medium"),
    ("1D DP", "Coin Change", "medium"),
    ("1D DP", "Maximum Product Subarray", "medium"),
    ("1D DP", "Word Break", "medium"),
    ("1D DP", "Longest Increasing Subsequence", "medium"),
    ("1D DP", "Partition Equal Subset Sum", "medium"),
    # 2D DP (11)
    ("2D DP", "Unique Paths", "medium"),
    ("2D DP", "Longest Common Subsequence", "medium"),
    ("2D DP", "Best Time to Buy and Sell Stock with Cooldown", "medium"),
    ("2D DP", "Coin Change II", "medium"),
    ("2D DP", "Target Sum", "medium"),
    ("2D DP", "Interleaving String", "medium"),
    ("2D DP", "Longest Increasing Path in a Matrix", "hard"),
    ("2D DP", "Distinct Subsequences", "hard"),
    ("2D DP", "Edit Distance", "medium"),
    ("2D DP", "Burst Balloons", "hard"),
    ("2D DP", "Regular Expression Matching", "hard"),
    # Greedy (8)
    ("Greedy", "Maximum Subarray", "medium"),
    ("Greedy", "Jump Game", "medium"),
    ("Greedy", "Jump Game II", "medium"),
    ("Greedy", "Gas Station", "medium"),
    ("Greedy", "Hand of Straights", "medium"),
    ("Greedy", "Merge Triplets to Form Target Triplet", "medium"),
    ("Greedy", "Partition Labels", "medium"),
    ("Greedy", "Valid Parenthesis String", "medium"),
    # Intervals (6)
    ("Intervals", "Insert Interval", "medium"),
    ("Intervals", "Merge Intervals", "medium"),
    ("Intervals", "Non-overlapping Intervals", "medium"),
    ("Intervals", "Meeting Rooms", "easy"),
    ("Intervals", "Meeting Rooms II", "medium"),
    ("Intervals", "Minimum Interval to Include Each Query", "hard"),
    # Math & Geometry (8)
    ("Math & Geometry", "Rotate Image", "medium"),
    ("Math & Geometry", "Spiral Matrix", "medium"),
    ("Math & Geometry", "Set Matrix Zeroes", "medium"),
    ("Math & Geometry", "Happy Number", "easy"),
    ("Math & Geometry", "Plus One", "easy"),
    ("Math & Geometry", "Pow(x, n)", "medium"),
    ("Math & Geometry", "Multiply Strings", "medium"),
    ("Math & Geometry", "Detect Squares", "medium"),
    # Bit Manipulation (7)
    ("Bit Manipulation", "Single Number", "easy"),
    ("Bit Manipulation", "Number of 1 Bits", "easy"),
    ("Bit Manipulation", "Counting Bits", "easy"),
    ("Bit Manipulation", "Reverse Bits", "easy"),
    ("Bit Manipulation", "Missing Number", "easy"),
    ("Bit Manipulation", "Sum of Two Integers", "medium"),
    ("Bit Manipulation", "Reverse Integer", "medium"),
]

TOPIC_ORDER = [
    "Arrays & Hashing", "Two Pointers", "Sliding Window", "Stack",
    "Binary Search", "Linked List", "Trees", "Tries",
    "Heap / Priority Queue", "Backtracking", "Graphs", "Advanced Graphs",
    "1D DP", "2D DP", "Greedy", "Intervals", "Math & Geometry", "Bit Manipulation",
]

assert len(NEETCODE_150) == 150, f"expected 150, got {len(NEETCODE_150)}"
